FROM blazemeter/taurus:latest
MAINTAINER blazemeter

ARG JMETER_VERSION=5.2.1
ENV JMETER_HOME /root/.bzt/jmeter-taurus/$JMETER_VERSION

ENV PATH $JMETER_HOME/bin:$PATH

USER root
EXPOSE 1099 50000

WORKDIR /tmp
RUN wget -q https://jmeter-plugins.org/files/packages/bzm-random-csv-0.8.zip \
&& unzip bzm-random-csv-0.8.zip \
&& cp lib/ext/jmeter-plugins-random-csv-data-set-0.8.jar ${JMETER_HOME}/lib/ext/ \
&& rm -rf bzm-random-csv-0.8.zip lib/
WORKDIR /bzt-configs

RUN ["sh", "-c", "chmod +x ${JMETER_HOME}/bin/jmeter-server"]
ENTRYPOINT ["sh", "-c", "${JMETER_HOME}/bin/jmeter-server -Dserver.rmi.localport=50000 -Dserver_port=1099 -Jserver.rmi.ssl.disable=true"]

