FROM blazemeter/taurus:latest
MAINTAINER blazemeter

ARG JMETER_VERSION=5.2.1
ENV JMETER_HOME /root/.bzt/jmeter-taurus/$JMETER_VERSION

ENV PATH $JMETER_HOME/bin:$PATH

USER root
EXPOSE 1099 50000

RUN ["sh", "-c", "chmod +x ${JMETER_HOME}/bin/jmeter-server"]
ENTRYPOINT ["sh", "-c", "${JMETER_HOME}/bin/jmeter-server -Dserver.rmi.localport=50000 -Dserver_port=1099 -Jserver.rmi.ssl.disable=true"]

